# Generated by Django 3.1.5 on 2021-01-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorski_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upisi',
            name='repeat_subj',
            field=models.IntegerField(default=0),
        ),
    ]
